### ISSUE TITLE
Prevent Google Maps UI Glitches

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/WP-Nebula#567]
Use this snippet in the CSS (and add it to the documentation somehow):

```css
#googlemap img {max-width: none;}
```
