### ISSUE TITLE
Consider a vertical align nebula class

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/WP-Nebula#647]
http://zerosixthree.se/vertical-align-anything-with-just-3-lines-of-css/

```css
/* Parent Element fix for blurry half-pixels */
.parent-element {
  -webkit-transform-style: preserve-3d;
  -moz-transform-style: preserve-3d;
  transform-style: preserve-3d;
}

.element {
  position: relative;
  top: 50%;
  transform: translateY(-50%);
}
```
