### ISSUE TITLE
Fix white submit button style

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/WP-Nebula#676]
This happens on a lot of default submit buttons. Fix it.

![screen shot 2015-06-04 at 9 08 58 am](https://cloud.githubusercontent.com/assets/6349678/7984767/681f9080-0a99-11e5-9912-3f09b76e46ee.png)

**Comment by chrisblakley** [comment]
```css
#searchsubmit {/* padding: 2px 5px !important; */ background: #1B74BB; border: 0; -webkit-transition: all 0.25s; -moz-transition: all 0.25s; -o-transition: all 0.25s; transition: all 0.25s;}
	#searchsubmit:hover,
	#searchsubmit.hover,
	#searchsubmit:focus {background: #2A388F;}
```
