### ISSUE TITLE
Add an example for a video "hero" section

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/WP-Nebula#688]
I'd like to have one page that is a sort of all-in-one example of a hero video section and even a modal on it that can trigger a play and pause of a youtube/vimeo video.

**Comment by chrisblakley** [comment]
Also describe specifically what video formats (and codecs) are needed to export along with ideal dimensions and file sizes. This should be a tool we can send to video personnel as needed.

**Comment by chrisblakley** [comment]
Here's a starting point:
```html
<?php $detect = new Mobile_Detect(); ?>
<?php if ($detect->isMobile() || $detect->isTablet()) : ?>

    <div id="ipad-slideshow">
		<ul>
			<li class="active"><img src="<?php bloginfo('template_directory');?>/images/still1.jpg"/></li>
			<li><img src="<?php bloginfo('template_directory');?>/images/still2.jpg"/></li>
			<li><img src="<?php bloginfo('template_directory');?>/images/still3.jpg"/></li>
			<li><img src="<?php bloginfo('template_directory');?>/images/still4.jpg"/></li>
			<li><img src="<?php bloginfo('template_directory');?>/images/still5.jpg"/></li>
		</ul>
	</div>

<?php else : ?>
	<video  id="video-background" width="640" height="360" autobuffer autoplay loop>
	 	<source src="<?php bloginfo('template_directory');?>/videos/homevid-REV.webm"  type="video/webm" />
	 	<source src="<?php bloginfo('template_directory');?>/videos/homevid-REV.mp4"  type="video/mp4" />
		<source src="<?php bloginfo('template_directory');?>/videos/homevid.ogv"  type="video/ogg" />

		<?php if(isset($_GET['debug'])){ ?>
		<object  id="video-background"  type="application/x-shockwave-flash" data="/wp-content/themes/BOU2014/videos/homevid_small.swf" style="width:100%;height:<?=$height;?>;z-index:0;">
			<param name="movie" value="/wp-content/themes/BOU2014/videos/homevid_small.swf" />
		</object>
		<?php }else{ ?>
		<object  id="video-background"  type="application/x-shockwave-flash" data="/wp-content/themes/BOU2014/videos/homevid.swf" style="width:100%;height:<?=$height;?>;z-index:0;">
			<param name="movie" value="/wp-content/themes/BOU2014/videos/homevid.swf" />

		<?php } ?>
		        <param name="wmode" value="transparent">
			<param name="scale" value="exactFit" />
			<param name="flashvars" value="autostart=true&amp;controlbar=none&amp;image=/wp-content/themes/BOU2014/images/homevid0001.jpg&amp;file=/wp-content/themes/BOU2014/videos/homevid.mp4" />
			<img src="/wp-content/themes/BOU2014/images/homevid0001.jpg" width="640" height="360" alt="BOU Video"
			     title="No video playback capabilities, please download the video below" />
		</object>
	</video>

<?php endif; ?>
```

Note there is a considerable amount of cleaning up needed here!

**Comment by chrisblakley** [comment]
```css
#video-background,
.mobile-video-background {position: absolute; bottom: 0px; right: 0px; top: 0px; left:0px; margin: auto; width: auto; height: auto; min-width: 100%; min-height: 100%; z-index: -1000; overflow: hidden;}
.mobile-video-background {display: none !important;}

@media only screen and (max-width: 767px) {
	#video-background {display: none !important;}
	.mobile-video-background {display: block !important;}
}
```
